[package]
name = "pyde-net"
license.workspace = true
version = "0.1.0"
edition = "2021"

[dependencies]
pyde-crypto = { path = "../crypto" }
pyde-account = { path = "../account" }
libp2p = { version = "0.54", features = ["tcp", "quic", "gossipsub", "kad", "noise", "yamux", "tokio", "macros", "identify", "request-response", "cbor", "serde"] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
getrandom = "0.2"

[dev-dependencies]
tokio = { version = "1", features = ["full", "test-util"] }
serde_json = "1"
futures = "0.3"

[lints]
workspace = true
