[package]
name = "pyde-state"
license.workspace = true
version.workspace = true
edition = "2021"

[dependencies]
pyde-crypto = { path = "../crypto" }
sparse-merkle-tree = "0.6"
jmt = { version = "0.12", default-features = false, features = ["std"] }
blake3 = "1"
anyhow = "1"
borsh = { version = "1", features = ["derive"] }
rocksdb = "0.24"
lru = "0.16"
tempfile = "3"

[[bench]]
name = "smt_bench"
harness = false

[lints]
workspace = true
