global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'pyde-validators'
    static_configs:
      - targets:
          - 'node-0:9090'
          - 'node-1:9091'
          - 'node-2:9092'
          - 'node-3:9093'
        labels:
          network: 'devnet'
