[package]
name = "pyde-consensus"
license.workspace = true
version = "0.1.0"
edition = "2021"

[dependencies]
pyde-crypto = { path = "../crypto" }
pyde-account = { path = "../account" }
pyde-tx = { path = "../tx" }
pyde-slashing = { path = "../slashing" }
sparse-merkle-tree = "0.6"

[dev-dependencies]
proptest = "1"

[lints]
workspace = true
