[package]
name = "pyde-aot"
license.workspace = true
version.workspace = true
edition = "2021"

[dependencies]
pyde-vm = { path = "../pvm" }
pyde-crypto = { path = "../crypto" }
cranelift-codegen = "0.131"
cranelift-frontend = "0.116"
cranelift-module = "0.116"
cranelift-jit = "0.116"
cranelift-native = "0.116"
target-lexicon = "0.12"

[dev-dependencies]
otic = { path = "../otic" }
pyde-crypto = { path = "../crypto" }
ethnum = "1"

[[bench]]
name = "aot_bench"
harness = false

[lints]
workspace = true
