[package]
name = "pyde-crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
p3-goldilocks = "0.4"
p3-field = "0.4"
p3-poseidon2 = "0.4"
p3-symmetric = "0.4"
falcon-rs = { version = "0.2", default-features = false, features = ["getrandom"] }
ml-kem = { version = "0.3.0-rc.0", default-features = false, features = ["getrandom"] }

[[bench]]
name = "poseidon2_bench"
harness = false

[[bench]]
name = "falcon_bench"
harness = false

[[bench]]
name = "threshold_bench"
harness = false

[[bench]]
name = "vrf_bench"
harness = false

[lints]
workspace = true
