[package]
name = "pyde-tx"
license.workspace = true
version = "0.1.0"
edition = "2021"

[dependencies]
pyde-crypto = { path = "../crypto" }
pyde-account = { path = "../account" }
pyde-vm = { path = "../pvm" }
pyde-state = { path = "../state" }
pyde-aot = { path = "../aot" }
pyde-slashing = { path = "../slashing" }
sparse-merkle-tree = "0.6"
tracing = "0.1"
hex = "0.4"
ethnum = "1.5.2"

[dev-dependencies]
otic = { path = "../otic" }
proptest = "1"

[lints]
workspace = true
